package domain

import "errors"

var (
	ErrContainerNotFound       = errors.New("container not found")
	ErrInvalidContainerStatus  = errors.New("invalid container status")
	ErrMissingRepository       = errors.New("missing dashboard repository")
	ErrAppNotFound             = errors.New("app not found")
	ErrMissingPlatformSettingsRepository = errors.New("missing platform settings repository")
	ErrDomainConflict          = errors.New("domain already in use")
	ErrInvalidDomain           = errors.New("invalid domain")
	ErrInvalidProxyPort        = errors.New("invalid proxy target port")
	ErrAdminPortConflict       = errors.New("proxy target port conflicts with admin port")
	ErrInvalidAppName          = errors.New("invalid app name")
	ErrComposeNoServices       = errors.New("compose yaml must contain a 'services:' key")
	ErrInvalidComposeYAML      = errors.New("invalid compose yaml")
	ErrMissingAppRepository    = errors.New("missing app repository")
	ErrMissingDockerRepository = errors.New("missing docker repository")
	ErrMissingGitRepository    = errors.New("missing git repository")
	ErrInvalidRepoURL          = errors.New("invalid repository URL")
	ErrUnsupportedRepoURL      = errors.New("unsupported repository URL")
	ErrRepoBranchNotFound      = errors.New("branch not found")
	ErrInvalidComposePath      = errors.New("invalid compose path")
	ErrMissingComposeFile      = errors.New("compose file is missing")
	ErrMissingDockerfile       = errors.New("missing Dockerfile")
	ErrInvalidAppPort          = errors.New("invalid app port")
	ErrComposeConfigValidation = errors.New("compose file validation failed")
	ErrReservedIngressPort     = errors.New("reserved ingress port in compose mapping")
	ErrManualCleanupRequired   = errors.New("manual cleanup required before delete")
	ErrTLSRequiresCertbot      = errors.New("TLS requires certificate management via certbot")
	ErrTLSEmailRequired        = errors.New("TLS requires certbot email to be configured")
	ErrTLSAgreementRequired    = errors.New("TLS requires certbot terms agreement")
)
