// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/a-h/templ"
	kitlayout "ui8kit/layout"
	kitui "ui8kit/ui"
)

const appDetailPaasScript = `function appId() {
  const root = document.getElementById('app-detail-root');
  return root ? root.dataset.appId || '' : '';
}
async function runAppAction(action) {
  const feedback = document.getElementById('app-feedback');
  const id = appId();
  if (feedback) feedback.textContent = 'Running ' + action + '...';
  const response = await fetch('/api/apps/' + encodeURIComponent(id) + '/' + action, { method: 'POST' });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    if (feedback) feedback.textContent = payload.error || 'Action failed';
    return;
  }
  window.location.reload();
}
async function deleteApp() {
  if (!confirm('Delete this application? All containers, volumes, and files will be permanently removed.')) return;
  const feedback = document.getElementById('app-feedback');
  const id = appId();
  if (feedback) feedback.textContent = 'Deleting...';
  const response = await fetch('/api/apps/' + encodeURIComponent(id), { method: 'DELETE' });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    if (feedback) feedback.textContent = payload.error || 'Delete failed';
    return;
  }
  window.location.href = '/apps';
}
function renderManagedEnv(env) {
  if (!env || typeof env !== 'object') return '';
  return Object.entries(env).map(([key, value]) => key + '=' + value).join('
');
}
function parseManagedEnv(text) {
  const values = {};
  const lines = text.split('
');
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const separator = line.indexOf('=');
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    if (!key) continue;
    values[key] = value;
  }
  return values;
}
async function loadAppConfig() {
  const response = await fetch('/api/apps/' + encodeURIComponent(appId()) + '/config', { method: 'GET' });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) return;
  const domainNode = document.getElementById('app-public-domain');
  const portNode = document.getElementById('app-proxy-target-port');
  const tlsNode = document.getElementById('app-use-tls');
  const envNode = document.getElementById('app-managed-env');
  if (domainNode) domainNode.value = payload.public_domain || '';
  if (portNode) portNode.value = payload.proxy_target_port ? String(payload.proxy_target_port) : '';
  if (tlsNode) tlsNode.checked = !!payload.use_tls;
  if (envNode) envNode.value = renderManagedEnv(payload.managed_env || {});
}
async function saveAppConfig() {
  const feedback = document.getElementById('app-config-feedback');
  if (feedback) feedback.textContent = 'Saving app settings...';
  const request = {
    public_domain: document.getElementById('app-public-domain').value.trim(),
    proxy_target_port: Number.parseInt(document.getElementById('app-proxy-target-port').value, 10) || 0,
    use_tls: !!document.getElementById('app-use-tls').checked,
    managed_env: parseManagedEnv(document.getElementById('app-managed-env').value),
  };
  const response = await fetch('/api/apps/' + encodeURIComponent(appId()) + '/config', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(request),
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    if (feedback) feedback.textContent = payload.error || 'Failed to save app settings';
    return;
  }
  if (feedback) feedback.textContent = 'App settings saved';
  await loadAppConfig();
}
document.addEventListener('DOMContentLoaded', loadAppConfig);`

func AppDetailPaasPage(data AppDetailPaasView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = kitlayout.Shell(kitlayout.ShellProps{Title: data.Title, Active: data.Active, NavItems: NavigationItems()}, AppDetailPaasContent(data)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func AppDetailPaasContent(data AppDetailPaasView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"app-detail-root\" data-app-id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.ID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 101, Col: 52}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"space-y-4\"><div class=\"flex items-start justify-between gap-3\"><div><div class=\"text-sm text-muted-foreground\">App ID: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.ID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 104, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><h2 class=\"text-2xl font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 105, Col: 50}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h2></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = StatusBadge(data.Status).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"grid gap-3 md:grid-cols-2\"><div class=\"card card-content space-y-2\"><div class=\"font-semibold\">Runtime</div><p class=\"text-sm text-muted-foreground\">Stack directory: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(data.Dir)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 112, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</p><p class=\"text-sm text-muted-foreground\">Ports: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(data.PortsStr)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 113, Col: 67}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p><p class=\"text-sm text-muted-foreground\">Updated: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(data.UpdatedAt)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 114, Col: 70}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</p></div><div class=\"card card-content space-y-3\"><div class=\"font-semibold\">Public access</div><label class=\"form-label\">Public domain")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "app-public-domain", Type: "text", Placeholder: "app.example.com"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</label><p class=\"text-xs text-muted-foreground\">Traffic starts as HTTP by default on the configured domain.</p><label class=\"form-label\">Proxy target port")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "app-proxy-target-port", Type: "number", Min: "1", Max: "65535", Placeholder: "3000"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</label><p class=\"text-xs text-muted-foreground\">Use the internal container port that the host nginx proxy should target on the managed Docker network.</p><label class=\"form-label-inline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "app-use-tls", Type: "checkbox"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<span>Enable HTTPS on proxy</span></label><p class=\"text-xs text-muted-foreground\">Enable HTTPS only after valid Let's Encrypt settings are configured; otherwise the app remains available on HTTP.</p><label class=\"form-label\">Managed environment variables")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "app-managed-env", Component: "textarea", Rows: 6}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</label> <button type=\"button\" class=\"rounded border border-border px-4 py-2 text-sm\" onclick=\"saveAppConfig()\">Save app settings</button><div id=\"app-config-feedback\" class=\"text-sm text-muted-foreground\"></div></div><div class=\"card card-content space-y-3\"><div class=\"font-semibold\">Actions</div><div class=\"flex flex-wrap gap-2\"><button class=\"rounded border border-border px-4 py-2 text-sm\" onclick=\"runAppAction('deploy')\">Deploy</button> <button class=\"rounded border border-border px-4 py-2 text-sm\" onclick=\"runAppAction('restart')\">Restart</button> <button class=\"rounded border border-border px-4 py-2 text-sm\" onclick=\"runAppAction('stop')\">Stop</button></div><div class=\"mt-2\"><button class=\"rounded border border-destructive px-4 py-2 text-sm text-destructive\" onclick=\"deleteApp()\">Delete</button></div><div id=\"app-feedback\" class=\"text-sm text-muted-foreground\"></div><div class=\"flex flex-wrap gap-2\"><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 templ.SafeURL
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinURLErrs("/apps/" + data.ID + "/compose")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 147, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" class=\"rounded border border-border px-4 py-2 text-sm\">Compose</a> <a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 templ.SafeURL
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinURLErrs("/apps/" + data.ID + "/logs")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `gui-docker/pages/app_detail_paas.templ`, Line: 148, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" class=\"rounded border border-border px-4 py-2 text-sm\">Logs</a></div></div></div><script>@templ.Raw(appDetailPaasScript)</script></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
