// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/a-h/templ"
	kitlayout "ui8kit/layout"
	kitui "ui8kit/ui"
)

const settingsScript = `async function loadAdminSettings() {
  const response = await fetch('/api/settings', { method: 'GET' });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) return;
  document.getElementById('admin-host').value = payload.admin_host || '';
  document.getElementById('admin-port').value = payload.admin_port ? String(payload.admin_port) : '';
  document.getElementById('admin-domain').value = payload.admin_domain || '';
  document.getElementById('admin-use-tls').checked = !!payload.admin_use_tls;
  document.getElementById('certbot-email').value = payload.certbot_email || '';
  document.getElementById('certbot-enabled').checked = !!payload.certbot_enabled;
  document.getElementById('certbot-staging').checked = !!payload.certbot_staging;
  document.getElementById('certbot-auto-renew').checked = payload.certbot_auto_renew !== false;
  document.getElementById('certbot-terms').checked = !!payload.certbot_terms_accepted;
}
async function saveAdminSettings() {
  const feedback = document.getElementById('admin-settings-feedback');
  if (feedback) feedback.textContent = 'Saving settings...';
  const payload = {
    admin_host: document.getElementById('admin-host').value.trim(),
    admin_port: Number.parseInt(document.getElementById('admin-port').value, 10) || 0,
    admin_domain: document.getElementById('admin-domain').value.trim(),
    admin_use_tls: !!document.getElementById('admin-use-tls').checked,
    certbot_email: document.getElementById('certbot-email').value.trim(),
    certbot_enabled: !!document.getElementById('certbot-enabled').checked,
    certbot_staging: !!document.getElementById('certbot-staging').checked,
    certbot_auto_renew: !!document.getElementById('certbot-auto-renew').checked,
    certbot_terms_accepted: !!document.getElementById('certbot-terms').checked,
  };
  const response = await fetch('/api/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) { if (feedback) feedback.textContent = body.error || 'Failed to save settings'; return; }
  if (feedback) feedback.textContent = 'Settings saved';
  await loadAdminSettings();
}
async function renewCertificates() {
  const feedback = document.getElementById('certbot-renew-feedback');
  if (feedback) feedback.textContent = 'Running renewal...';
  const response = await fetch('/api/certificates/renew', { method: 'POST' });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) { if (feedback) feedback.textContent = body.error || 'Certificate renewal failed'; return; }
  if (feedback) feedback.textContent = body.message || 'Certificate renewal completed';
}
document.addEventListener('DOMContentLoaded', loadAdminSettings);`

func SettingsPage(data LayoutData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = kitlayout.Shell(kitlayout.ShellProps{Title: data.Title, Active: data.Active, NavItems: NavigationItems()}, SettingsContent(data)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SettingsContent(data LayoutData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"space-y-4\"><div><div class=\"text-2xl font-semibold\">Settings</div><div class=\"text-sm text-muted-foreground\">Manage platform endpoint settings used by the admin API and external access.</div></div><div class=\"grid gap-3 md:grid-cols-2\"><div class=\"card card-content\"><div class=\"font-semibold\">Admin panel endpoint</div><div class=\"space-y-3\"><label class=\"form-label\">Admin host")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "admin-host", Placeholder: "0.0.0.0"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</label> <label class=\"form-label\">Admin port")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "admin-port", Type: "number", Min: "1", Max: "65535", Placeholder: "3000"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</label> <label class=\"form-label\">Admin domain (optional)")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "admin-domain", Placeholder: "dashboard.example.com"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</label> <label class=\"form-label-inline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "admin-use-tls", Type: "checkbox"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<span>Enable HTTPS for admin endpoint</span></label> <label class=\"form-label\">Let's Encrypt email")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "certbot-email", Placeholder: "admin@example.com"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</label> <label class=\"form-label-inline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "certbot-enabled", Type: "checkbox"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<span>Enable certificate automation</span></label> <label class=\"form-label-inline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "certbot-staging", Type: "checkbox"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<span>Use Let's Encrypt staging environment</span></label> <label class=\"form-label-inline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "certbot-auto-renew", Type: "checkbox", Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span>Enable automatic renewal</span></label><p class=\"mt-1 text-xs text-muted-foreground\">Renewal uses the host-installed <code>certbot</code> binary through the dashboard controller container. If you disable automatic renewal, add a manual renewal schedule and keep host <code>nginx</code> reload enabled after renewal.</p><label class=\"form-label-inline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = kitui.Field(kitui.FieldProps{ID: "certbot-terms", Type: "checkbox"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<span>I accept Let's Encrypt terms of service</span></label> <button type=\"button\" class=\"rounded border border-border px-4 py-2 text-sm\" onclick=\"saveAdminSettings()\">Save admin settings</button><div id=\"admin-settings-feedback\" class=\"text-sm text-muted-foreground\"></div><button type=\"button\" class=\"rounded border border-border px-4 py-2 text-sm\" onclick=\"renewCertificates()\">Run certificate renewal now</button><div id=\"certbot-renew-feedback\" class=\"text-sm text-muted-foreground\"></div></div></div><div class=\"card card-content\"><div class=\"font-semibold\">Notes</div><ul class=\"list-inside list-disc space-y-2 text-sm text-muted-foreground\"><li>Platform exposes this config through <code>/api/settings</code>.</li><li>When domain is not set, the panel is reachable via host IP.</li><li>TLS settings are applied only when \"Enable HTTPS on proxy\" is enabled for an app.</li><li>Certificates are issued and removed against the host installation of <code>certbot</code>.</li><li>Host <code>nginx</code> owns ports 80/443 and keeps routing active even if the dashboard container is removed.</li></ul></div></div><script>@templ.Raw(settingsScript)</script></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
