// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/a-h/templ"

type ShellProps struct {
	Title    string
	Active   string
	NavItems []NavItem
}

const shellThemeScript = `(function () {
  const root = document.documentElement;
  const themeIcon = () => document.getElementById('theme-toggle-icon');
  const savedTheme = localStorage.getItem('dashboard-theme');
  const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
  const shouldUseDark = savedTheme === 'dark' || (!savedTheme && prefersDark);
  const applyThemeIcon = () => {
    const icon = themeIcon();
    if (!icon) return;
    icon.className = root.classList.contains('dark') ? 'latty latty-sun h-4 w-4' : 'latty latty-moon h-4 w-4';
  };
  root.classList.toggle('dark', shouldUseDark);
  applyThemeIcon();
  window.toggleDashboardTheme = function () {
    const nextDark = !root.classList.contains('dark');
    root.classList.toggle('dark', nextDark);
    localStorage.setItem('dashboard-theme', nextDark ? 'dark' : 'light');
    applyThemeIcon();
  };
  document.addEventListener('DOMContentLoaded', applyThemeIcon);
})();`

const shellPageScript = `window.openMobileSidebar = function () {
  const sidebar = document.getElementById('mobile-sidebar');
  const backdrop = document.getElementById('mobile-sidebar-backdrop');
  if (!sidebar || !backdrop) return;
  sidebar.classList.remove('hidden');
  backdrop.classList.remove('hidden');
  document.body.style.overflow = 'hidden';
};
window.closeMobileSidebar = function () {
  const sidebar = document.getElementById('mobile-sidebar');
  const backdrop = document.getElementById('mobile-sidebar-backdrop');
  if (!sidebar || !backdrop) return;
  sidebar.classList.add('hidden');
  backdrop.classList.add('hidden');
  document.body.style.overflow = '';
};
window.addEventListener('keydown', function (event) {
  if (event && event.key === 'Escape') closeMobileSidebar();
});
const sidebarElement = document.getElementById('mobile-sidebar');
if (sidebarElement) {
  let sidebarTouchStartX = 0;
  sidebarElement.addEventListener('touchstart', function (event) {
    if (event.touches.length > 0) sidebarTouchStartX = event.touches[0].clientX;
  }, { passive: true });
  sidebarElement.addEventListener('touchend', function (event) {
    if (!event.changedTouches || event.changedTouches.length === 0) return;
    const touchEndX = event.changedTouches[0].clientX;
    if (sidebarTouchStartX - touchEndX > 60) closeMobileSidebar();
  }, { passive: true });
}
window.showComposeMessage = function (message) {
  const composeTarget = document.getElementById('compose-status');
  if (composeTarget) { composeTarget.textContent = message; return; }
  const appFeedback = document.getElementById('app-feedback');
  if (appFeedback) appFeedback.textContent = message;
};
window.updateContainerStatus = async function (containerID, status) {
  try {
    const response = await fetch('/api/containers/' + encodeURIComponent(containerID), {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: status }),
    });
    const data = await response.json();
    if (data && data.success) location.reload();
  } catch (err) {
    console.error('Action failed:', err);
  }
};`

func Shell(props ShellProps, content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui8kit/layout/shell.templ`, Line: 90, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"><link rel=\"icon\" type=\"image/svg+xml\" href=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NyA0MCIgZmlsbD0iIzBlYTVlOSI+DQogICAgPHBhdGggZD0iTTIzLjUgNi41QzE3LjUgNi41IDEzLjc1IDkuNSAxMi4yNSAxNS41QzE0LjUgMTIuNSAxNy4xMjUgMTEuMzc1IDIwLjEyNSAxMi4xMjVDMjEuODM2NyAxMi41NTI5IDIzLjA2MDEgMTMuNzk0NyAyNC40MTQyIDE1LjE2OTJDMjYuNjIwMiAxNy40MDg0IDI5LjE3MzQgMjAgMzQuNzUgMjBDNDAuNzUgMjAgNDQuNSAxNyA0NiAxMUM0My43NSAxNCA0MS4xMjUgMTUuMTI1IDM4LjEyNSAxNC4zNzVDMzYuNDEzMyAxMy45NDcxIDM1LjE4OTkgMTIuNzA1MyAzMy44MzU3IDExLjMzMDhDMzEuNjI5NyA5LjA5MTU4IDI5LjA3NjYgNi41IDIzLjUgNi41Wk0xMi4yNSAyMEM2LjI1IDIwIDIuNSAyMyAxIDI5QzMuMjUgMjYgNS44NzUgMjQuODc1IDguODc1IDI1LjYyNUMxMC41ODY3IDI2LjA1MjkgMTEuODEwMSAyNy4yOTQ3IDEzLjE2NDIgMjguNjY5M0MxNS4zNzAyIDMwLjkwODQgMTcuOTIzNCAzMy41IDIzLjUgMzMuNUMyOS41IDMzLjUgMzMuMjUgMzAuNSAzNC43NSAyNC41QzMyLjUgMjcuNSAyOS44NzUgMjguNjI1IDI2Ljg3NSAyNy44NzVDMjUuMTYzMyAyNy40NDcxIDIzLjkzOTkgMjYuMjA1MyAyMi41ODU4IDI0LjgzMDdDMjAuMzc5OCAyMi41OTE2IDE3LjgyNjYgMjAgMTIuMjUgMjBaIj48L3BhdGg+DQo8L3N2Zz4=\"><script>@templ.Raw(shellThemeScript)</script></head><body class=\"min-h-screen overflow-x-hidden bg-background font-sans text-foreground\"><div id=\"mobile-sidebar-backdrop\" class=\"fixed inset-0 z-30 hidden\" onclick=\"closeMobileSidebar()\" style=\"background: rgba(0, 0, 0, 0.45);\"></div><aside id=\"mobile-sidebar\" class=\"fixed bottom-0 left-0 top-0 z-40 hidden w-64 max-w-full border-r border-border bg-card md:hidden\"><div class=\"flex h-15 items-center justify-between border-b border-border px-4\"><div><p class=\"font-bold\">Local Panel</p></div><button onclick=\"closeMobileSidebar()\" class=\"rounded border border-border px-2 py-1 text-xs\">Close</button></div><nav class=\"space-y-1 p-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Sidebar(SidebarProps{Items: props.NavItems, Active: props.Active, Mobile: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</nav></aside><div class=\"flex min-h-screen w-full\"><aside class=\"hidden border-r border-border bg-card md:block md:w-64\"><div class=\"flex h-15 items-center border-b border-border px-4\"><p class=\"font-bold\">Local Panel</p></div><nav class=\"space-y-1 p-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Sidebar(SidebarProps{Items: props.NavItems, Active: props.Active}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</nav></aside><div class=\"flex min-w-0 flex-1 flex-col\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header(HeaderProps{Title: props.Title}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<main class=\"w-full min-w-0 max-w-full p-4 md:p-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</main></div></div><script>@templ.Raw(shellPageScript)</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
